name: CI

on:
  push:
    paths:
      - '.github/workflows/*.yml'
      - 'src/**'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/*.yml'
      - 'src/**'

jobs:
  lint-and-security-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install linting and security check dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 bandit
      - name: Lint source code
        run: flake8
      - name: Check code for high severity level vulnerabilities
        run: bandit -lll src/main/**/*.py

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest coverage httpx genbadge[coverage]
      - name: Run tests
        run: coverage run -m pytest
      - name: Generate coverage report
        run: coverage xml
      - name: Generate coverage badge
        run: |
          mkdir -p .github/badges
          genbadge coverage -i coverage.xml -o .github/badges/coverage.svg
      - name: Commit and push coverage badge
        env:
          PAT_GITHUB: ${{ secrets.PAT_GITHUB }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .github/badges/coverage.svg
          git commit -m "Update coverage badge" || echo "No changes to commit"
          git push https://x-access-token:${PAT_GITHUB}@github.com/${{ github.repository }}.git HEAD:main
